# Site settings
author: Irene Saez
title: Code Discoveries
header-img: img/home-bg.png
email: bluemilk44@gmail.com
copyright_name: Irene Saez
description: > # this means to ignore newlines until "baseurl:"
  Things learned while coding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  blitzparanoia

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
